/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type Order = {
  _id: string;
  _type: "order";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  orderNumber?: string;
  stripeCheckoutSessionId?: string;
  stripeCustomerId?: string;
  clerkUserId?: string;
  customerName?: string;
  email?: string;
  stripePaymentIntentId?: string;
  products?: Array<{
    product?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "product";
    };
    quantity?: number;
    _key: string;
  }>;
  totalPrice?: number;
  currency?: string;
  amountDiscount?: number;
  status?: "pending" | "paid" | "shipped" | "delivered" | "cancelled";
  orderDate?: string;
};

export type Category = {
  _id: string;
  _type: "category";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  description?: string;
};

export type Sale = {
  _id: string;
  _type: "sale";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  name?: string;
  description?: string;
  badge?: string;
  discountAmount?: number;
  couponCode?: string;
  validFrom?: string;
  validUntil?: string;
  isActive?: boolean;
  image?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
};

export type Product = {
  _id: string;
  _type: "product";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  image?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  price?: number;
  description?: string;
  discount?: number;
  priceWithoutDiscount?: number;
  isFeaturedProduct?: boolean;
  stock?: number;
  category?: "Chair" | "Sofa";
  status?: "new" | "hot" | "sale";
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type AllSanitySchemaTypes = SanityImagePaletteSwatch | SanityImagePalette | SanityImageDimensions | SanityFileAsset | Geopoint | Order | Category | Sale | Product | SanityImageCrop | SanityImageHotspot | SanityImageAsset | SanityAssetSourceData | SanityImageMetadata | Slug;
export declare const internalGroqTypeReferenceTo: unique symbol;
// Source: ./sanity/lib/quires.ts
// Variable: allProducts
// Query: *[_type == "product"]{  _id,  _type,  _createdAt,  _updatedAt,  _rev,  name,  slug ,  image { asset { _ref, _type } },  price,  description,  discount,  priceWithoutDiscount,  isFeaturedProduct,  stock,  category,  status    }
export type AllProductsResult = Array<{
  _id: string;
  _type: "product";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string | null;
  slug: Slug | null;
  image: {
    asset: {
      _ref: string;
      _type: "reference";
    } | null;
  } | null;
  price: number | null;
  description: string | null;
  discount: number | null;
  priceWithoutDiscount: number | null;
  isFeaturedProduct: boolean | null;
  stock: number | null;
  category: "Chair" | "Sofa" | null;
  status: "hot" | "new" | "sale" | null;
}>;
// Variable: sixPro
// Query: *[_type == "product" ][11..16]{   _id,  _type,  _createdAt,  _updatedAt,  _rev,  name,  slug ,  image { asset { _ref, _type } },  price,  description,  discount,  priceWithoutDiscount,  isFeaturedProduct,  stock,  category,  status    }
export type SixProResult = Array<{
  _id: string;
  _type: "product";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string | null;
  slug: Slug | null;
  image: {
    asset: {
      _ref: string;
      _type: "reference";
    } | null;
  } | null;
  price: number | null;
  description: string | null;
  discount: number | null;
  priceWithoutDiscount: number | null;
  isFeaturedProduct: boolean | null;
  stock: number | null;
  category: "Chair" | "Sofa" | null;
  status: "hot" | "new" | "sale" | null;
}>;
// Variable: Chairs
// Query: *[_type == "product" ][12..15]{   _id,  _type,  _createdAt,  _updatedAt,  _rev,  name,  slug ,  image { asset { _ref, _type } },  price,  description,  discount,  priceWithoutDiscount,  isFeaturedProduct,  stock,  category,  status    }
export type ChairsResult = Array<{
  _id: string;
  _type: "product";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string | null;
  slug: Slug | null;
  image: {
    asset: {
      _ref: string;
      _type: "reference";
    } | null;
  } | null;
  price: number | null;
  description: string | null;
  discount: number | null;
  priceWithoutDiscount: number | null;
  isFeaturedProduct: boolean | null;
  stock: number | null;
  category: "Chair" | "Sofa" | null;
  status: "hot" | "new" | "sale" | null;
}>;
// Variable: fourPro
// Query: *[_type == "product" && category == "Chair" ][5..8]{   _id,  _type,  _createdAt,  _updatedAt,  _rev,  name,  slug ,  image { asset { _ref, _type } },  price,  description,  discount,  priceWithoutDiscount,  isFeaturedProduct,  stock,  category,  status    }
export type FourProResult = Array<{
  _id: string;
  _type: "product";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string | null;
  slug: Slug | null;
  image: {
    asset: {
      _ref: string;
      _type: "reference";
    } | null;
  } | null;
  price: number | null;
  description: string | null;
  discount: number | null;
  priceWithoutDiscount: number | null;
  isFeaturedProduct: boolean | null;
  stock: number | null;
  category: "Chair" | "Sofa" | null;
  status: "hot" | "new" | "sale" | null;
}>;
// Variable: Featured
// Query: *[_type == "product"] | order(_createdAt desc)[0...4] {   _id,  _type,  _createdAt,  _updatedAt,  _rev,  name,  slug ,  image { asset { _ref, _type } },  price,  description,  discount,  priceWithoutDiscount,  isFeaturedProduct,  stock,  category,  status}
export type FeaturedResult = Array<{
  _id: string;
  _type: "product";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string | null;
  slug: Slug | null;
  image: {
    asset: {
      _ref: string;
      _type: "reference";
    } | null;
  } | null;
  price: number | null;
  description: string | null;
  discount: number | null;
  priceWithoutDiscount: number | null;
  isFeaturedProduct: boolean | null;
  stock: number | null;
  category: "Chair" | "Sofa" | null;
  status: "hot" | "new" | "sale" | null;
}>;
// Variable: Unique
// Query: *[_type == "product" &&  name == "Stylish Golden Metal Legs Mint Blue Fabric Velvet Sofa Leisure Armchair"]{    _id,  _type,  _createdAt,  _updatedAt,  _rev,  name,  slug ,  image { asset { _ref, _type } },  price,  description,  discount,  priceWithoutDiscount,  isFeaturedProduct,  stock,  category,  status      }
export type UniqueResult = Array<{
  _id: string;
  _type: "product";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string | null;
  slug: Slug | null;
  image: {
    asset: {
      _ref: string;
      _type: "reference";
    } | null;
  } | null;
  price: number | null;
  description: string | null;
  discount: number | null;
  priceWithoutDiscount: number | null;
  isFeaturedProduct: boolean | null;
  stock: number | null;
  category: "Chair" | "Sofa" | null;
  status: "hot" | "new" | "sale" | null;
}>;
// Variable: Hero
// Query: *[_type == "product" &&  name == "Luxury Flower Shell Sofa Chair"]{      _id,  _type,  _createdAt,  _updatedAt,  _rev,  name,  slug ,  image { asset { _ref, _type } },  price,  description,  discount,  priceWithoutDiscount,  isFeaturedProduct,  stock,  category,  status      }
export type HeroResult = Array<{
  _id: string;
  _type: "product";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string | null;
  slug: Slug | null;
  image: {
    asset: {
      _ref: string;
      _type: "reference";
    } | null;
  } | null;
  price: number | null;
  description: string | null;
  discount: number | null;
  priceWithoutDiscount: number | null;
  isFeaturedProduct: boolean | null;
  stock: number | null;
  category: "Chair" | "Sofa" | null;
  status: "hot" | "new" | "sale" | null;
}>;
// Variable: DiscountQuery
// Query: *[_type == "product" &&  name == "Armchair Tortuga"]{     _id,  _type,  _createdAt,  _updatedAt,  _rev,  name,  slug ,  image { asset { _ref, _type } },  price,  description,  discount,  priceWithoutDiscount,  isFeaturedProduct,  stock,  category,  status      }
export type DiscountQueryResult = Array<{
  _id: string;
  _type: "product";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string | null;
  slug: Slug | null;
  image: {
    asset: {
      _ref: string;
      _type: "reference";
    } | null;
  } | null;
  price: number | null;
  description: string | null;
  discount: number | null;
  priceWithoutDiscount: number | null;
  isFeaturedProduct: boolean | null;
  stock: number | null;
  category: "Chair" | "Sofa" | null;
  status: "hot" | "new" | "sale" | null;
}>;
// Variable: FirstQuery
// Query: *[_type == "product" &&  name == "Nautilus Lounge Chair"]{     _id,  _type,  _createdAt,  _updatedAt,  _rev,  name,  slug ,  image { asset { _ref, _type } },  price,  description,  discount,  priceWithoutDiscount,  isFeaturedProduct,  stock,  category,  status      }
export type FirstQueryResult = Array<{
  _id: string;
  _type: "product";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string | null;
  slug: Slug | null;
  image: {
    asset: {
      _ref: string;
      _type: "reference";
    } | null;
  } | null;
  price: number | null;
  description: string | null;
  discount: number | null;
  priceWithoutDiscount: number | null;
  isFeaturedProduct: boolean | null;
  stock: number | null;
  category: "Chair" | "Sofa" | null;
  status: "hot" | "new" | "sale" | null;
}>;
// Variable: SecondQuery
// Query: *[_type == "product" &&  name == "Replica Hans Wegner Wishbone Chair"]{     _id,  _type,  _createdAt,  _updatedAt,  _rev,  name,  slug ,  image { asset { _ref, _type } },  price,  description,  discount,  priceWithoutDiscount,  isFeaturedProduct,  stock,  category,  status      }
export type SecondQueryResult = Array<{
  _id: string;
  _type: "product";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string | null;
  slug: Slug | null;
  image: {
    asset: {
      _ref: string;
      _type: "reference";
    } | null;
  } | null;
  price: number | null;
  description: string | null;
  discount: number | null;
  priceWithoutDiscount: number | null;
  isFeaturedProduct: boolean | null;
  stock: number | null;
  category: "Chair" | "Sofa" | null;
  status: "hot" | "new" | "sale" | null;
}>;
// Variable: ThirdQuery
// Query: *[_type == "product" &&  name == "Alpha Chair – Solid Ebonised Oak"]{    _id,  _type,  _createdAt,  _updatedAt,  _rev,  name,  slug ,  image { asset { _ref, _type } },  price,  description,  discount,  priceWithoutDiscount,  isFeaturedProduct,  stock,  category,  status      }
export type ThirdQueryResult = Array<{
  _id: string;
  _type: "product";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string | null;
  slug: Slug | null;
  image: {
    asset: {
      _ref: string;
      _type: "reference";
    } | null;
  } | null;
  price: number | null;
  description: string | null;
  discount: number | null;
  priceWithoutDiscount: number | null;
  isFeaturedProduct: boolean | null;
  stock: number | null;
  category: "Chair" | "Sofa" | null;
  status: "hot" | "new" | "sale" | null;
}>;
// Variable: ItemQuery
// Query: *[_type == "product" &&  name == "Liberty Wood 63' Floating Entertainment Center"]{       _id,  _type,  _createdAt,  _updatedAt,  _rev,  name,  slug ,  image { asset { _ref, _type } },  price,  description,  discount,  priceWithoutDiscount,  isFeaturedProduct,  stock,  category,  status        }
export type ItemQueryResult = Array<{
  _id: string;
  _type: "product";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string | null;
  slug: Slug | null;
  image: {
    asset: {
      _ref: string;
      _type: "reference";
    } | null;
  } | null;
  price: number | null;
  description: string | null;
  discount: number | null;
  priceWithoutDiscount: number | null;
  isFeaturedProduct: boolean | null;
  stock: number | null;
  category: "Chair" | "Sofa" | null;
  status: "hot" | "new" | "sale" | null;
}>;
// Variable: Slug
// Query: *[_type == "product" &&  _id == $_id][0]{       _id,  _type,  _createdAt,  _updatedAt,  _rev,  name,  slug ,  image { asset { _ref, _type } },  price,  description,  discount,  priceWithoutDiscount,  isFeaturedProduct,  stock,  category,  status        }
export type SlugResult = {
  _id: string;
  _type: "product";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string | null;
  slug: Slug | null;
  image: {
    asset: {
      _ref: string;
      _type: "reference";
    } | null;
  } | null;
  price: number | null;
  description: string | null;
  discount: number | null;
  priceWithoutDiscount: number | null;
  isFeaturedProduct: boolean | null;
  stock: number | null;
  category: "Chair" | "Sofa" | null;
  status: "hot" | "new" | "sale" | null;
} | null;

// Source: ./sanity/helpers/index.ts
// Variable: PRODUCTS_QUERY
// Query: *[_type=="product"] | order(name asc)
export type PRODUCTS_QUERYResult = Array<{
  _id: string;
  _type: "product";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  image?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  price?: number;
  description?: string;
  discount?: number;
  priceWithoutDiscount?: number;
  isFeaturedProduct?: boolean;
  stock?: number;
  category?: "Chair" | "Sofa";
  status?: "hot" | "new" | "sale";
}>;
// Variable: CATEGORIES_QUERY
// Query: *[_type=="category"] | order(name asc)
export type CATEGORIES_QUERYResult = Array<{
  _id: string;
  _type: "category";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  description?: string;
}>;
// Variable: ACTIVE_COUPON_CODE
// Query: *[_type == 'sale' && isActive == true && couponCode == $couponCode] | order(validFrom desc)[0]
export type ACTIVE_COUPON_CODEResult = {
  _id: string;
  _type: "sale";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  name?: string;
  description?: string;
  badge?: string;
  discountAmount?: number;
  couponCode?: string;
  validFrom?: string;
  validUntil?: string;
  isActive?: boolean;
  image?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
} | null;
// Variable: PRODUCT_SEARCH_QUERY
// Query: *[_type == "product" && name match $searchParam] | order(name asc)
export type PRODUCT_SEARCH_QUERYResult = Array<{
  _id: string;
  _type: "product";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  image?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  price?: number;
  description?: string;
  discount?: number;
  priceWithoutDiscount?: number;
  isFeaturedProduct?: boolean;
  stock?: number;
  category?: "Chair" | "Sofa";
  status?: "hot" | "new" | "sale";
}>;
// Variable: PRODUCT_BY_ID_QUERY
// Query: *[_type == "product" && slug.current == $slug ] | order(name asc) [0]
export type PRODUCT_BY_ID_QUERYResult = {
  _id: string;
  _type: "product";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  image?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  price?: number;
  description?: string;
  discount?: number;
  priceWithoutDiscount?: number;
  isFeaturedProduct?: boolean;
  stock?: number;
  category?: "Chair" | "Sofa";
  status?: "hot" | "new" | "sale";
} | null;
// Variable: PRODUCT_BY_CATEGORY_QUERY
// Query: *[_type == "product" && references(*[_type == "category" && slug.current == $categorySlug]._id)] | order(name asc)
export type PRODUCT_BY_CATEGORY_QUERYResult = Array<{
  _id: string;
  _type: "product";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  image?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  price?: number;
  description?: string;
  discount?: number;
  priceWithoutDiscount?: number;
  isFeaturedProduct?: boolean;
  stock?: number;
  category?: "Chair" | "Sofa";
  status?: "hot" | "new" | "sale";
}>;
// Variable: SALE_QUERY
// Query: *[_type == 'sale'] | order(name asc)
export type SALE_QUERYResult = Array<{
  _id: string;
  _type: "sale";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  name?: string;
  description?: string;
  badge?: string;
  discountAmount?: number;
  couponCode?: string;
  validFrom?: string;
  validUntil?: string;
  isActive?: boolean;
  image?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
}>;
// Variable: MY_ORDERS_QUERY
// Query: *[_type == 'order' && clerkUserId == $userId] | order(orderData desc){    ...,products[]{      ...,product->    }  }
export type MY_ORDERS_QUERYResult = Array<{
  _id: string;
  _type: "order";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  orderNumber?: string;
  stripeCheckoutSessionId?: string;
  stripeCustomerId?: string;
  clerkUserId?: string;
  customerName?: string;
  email?: string;
  stripePaymentIntentId?: string;
  products: Array<{
    product: {
      _id: string;
      _type: "product";
      _createdAt: string;
      _updatedAt: string;
      _rev: string;
      name?: string;
      slug?: Slug;
      image?: {
        asset?: {
          _ref: string;
          _type: "reference";
          _weak?: boolean;
          [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
        };
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: "image";
      };
      price?: number;
      description?: string;
      discount?: number;
      priceWithoutDiscount?: number;
      isFeaturedProduct?: boolean;
      stock?: number;
      category?: "Chair" | "Sofa";
      status?: "hot" | "new" | "sale";
    } | null;
    quantity?: number;
    _key: string;
  }> | null;
  totalPrice?: number;
  currency?: string;
  amountDiscount?: number;
  status?: "cancelled" | "delivered" | "paid" | "pending" | "shipped";
  orderDate?: string;
}>;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    "*[_type == \"product\"]{\n  _id,\n  _type,\n  _createdAt,\n  _updatedAt,\n  _rev,\n  name,\n  slug ,\n  image { asset { _ref, _type } },\n  price,\n  description,\n  discount,\n  priceWithoutDiscount,\n  isFeaturedProduct,\n  stock,\n  category,\n  status\n    }": AllProductsResult;
    "*[_type == \"product\" ][11..16]{\n   _id,\n  _type,\n  _createdAt,\n  _updatedAt,\n  _rev,\n  name,\n  slug ,\n  image { asset { _ref, _type } },\n  price,\n  description,\n  discount,\n  priceWithoutDiscount,\n  isFeaturedProduct,\n  stock,\n  category,\n  status\n    }": SixProResult;
    "*[_type == \"product\" ][12..15]{\n   _id,\n  _type,\n  _createdAt,\n  _updatedAt,\n  _rev,\n  name,\n  slug ,\n  image { asset { _ref, _type } },\n  price,\n  description,\n  discount,\n  priceWithoutDiscount,\n  isFeaturedProduct,\n  stock,\n  category,\n  status\n    }": ChairsResult;
    "*[_type == \"product\" && category == \"Chair\" ][5..8]{\n   _id,\n  _type,\n  _createdAt,\n  _updatedAt,\n  _rev,\n  name,\n  slug ,\n  image { asset { _ref, _type } },\n  price,\n  description,\n  discount,\n  priceWithoutDiscount,\n  isFeaturedProduct,\n  stock,\n  category,\n  status\n    }": FourProResult;
    "*[_type == \"product\"] | order(_createdAt desc)[0...4] {\n   _id,\n  _type,\n  _createdAt,\n  _updatedAt,\n  _rev,\n  name,\n  slug ,\n  image { asset { _ref, _type } },\n  price,\n  description,\n  discount,\n  priceWithoutDiscount,\n  isFeaturedProduct,\n  stock,\n  category,\n  status\n}": FeaturedResult;
    "*[_type == \"product\" &&  name == \"Stylish Golden Metal Legs Mint Blue Fabric Velvet Sofa Leisure Armchair\"]{\n    _id,\n  _type,\n  _createdAt,\n  _updatedAt,\n  _rev,\n  name,\n  slug ,\n  image { asset { _ref, _type } },\n  price,\n  description,\n  discount,\n  priceWithoutDiscount,\n  isFeaturedProduct,\n  stock,\n  category,\n  status\n      }": UniqueResult;
    "*[_type == \"product\" &&  name == \"Luxury Flower Shell Sofa Chair\"]{\n      _id,\n  _type,\n  _createdAt,\n  _updatedAt,\n  _rev,\n  name,\n  slug ,\n  image { asset { _ref, _type } },\n  price,\n  description,\n  discount,\n  priceWithoutDiscount,\n  isFeaturedProduct,\n  stock,\n  category,\n  status\n      }": HeroResult;
    "*[_type == \"product\" &&  name == \"Armchair Tortuga\"]{\n     _id,\n  _type,\n  _createdAt,\n  _updatedAt,\n  _rev,\n  name,\n  slug ,\n  image { asset { _ref, _type } },\n  price,\n  description,\n  discount,\n  priceWithoutDiscount,\n  isFeaturedProduct,\n  stock,\n  category,\n  status\n      }": DiscountQueryResult;
    "*[_type == \"product\" &&  name == \"Nautilus Lounge Chair\"]{\n     _id,\n  _type,\n  _createdAt,\n  _updatedAt,\n  _rev,\n  name,\n  slug ,\n  image { asset { _ref, _type } },\n  price,\n  description,\n  discount,\n  priceWithoutDiscount,\n  isFeaturedProduct,\n  stock,\n  category,\n  status\n      }": FirstQueryResult;
    "*[_type == \"product\" &&  name == \"Replica Hans Wegner Wishbone Chair\"]{\n     _id,\n  _type,\n  _createdAt,\n  _updatedAt,\n  _rev,\n  name,\n  slug ,\n  image { asset { _ref, _type } },\n  price,\n  description,\n  discount,\n  priceWithoutDiscount,\n  isFeaturedProduct,\n  stock,\n  category,\n  status\n      }": SecondQueryResult;
    "*[_type == \"product\" &&  name == \"Alpha Chair \u2013 Solid Ebonised Oak\"]{\n    _id,\n  _type,\n  _createdAt,\n  _updatedAt,\n  _rev,\n  name,\n  slug ,\n  image { asset { _ref, _type } },\n  price,\n  description,\n  discount,\n  priceWithoutDiscount,\n  isFeaturedProduct,\n  stock,\n  category,\n  status\n      }": ThirdQueryResult;
    "*[_type == \"product\" &&  name == \"Liberty Wood 63' Floating Entertainment Center\"]{\n       _id,\n  _type,\n  _createdAt,\n  _updatedAt,\n  _rev,\n  name,\n  slug ,\n  image { asset { _ref, _type } },\n  price,\n  description,\n  discount,\n  priceWithoutDiscount,\n  isFeaturedProduct,\n  stock,\n  category,\n  status\n        }": ItemQueryResult;
    "*[_type == \"product\" &&  _id == $_id][0]{\n       _id,\n  _type,\n  _createdAt,\n  _updatedAt,\n  _rev,\n  name,\n  slug ,\n  image { asset { _ref, _type } },\n  price,\n  description,\n  discount,\n  priceWithoutDiscount,\n  isFeaturedProduct,\n  stock,\n  category,\n  status\n        }": SlugResult;
    "*[_type==\"product\"] | order(name asc)": PRODUCTS_QUERYResult;
    "*[_type==\"category\"] | order(name asc)": CATEGORIES_QUERYResult;
    "*[_type == 'sale' && isActive == true && couponCode == $couponCode] | order(validFrom desc)[0]": ACTIVE_COUPON_CODEResult;
    "*[_type == \"product\" && name match $searchParam] | order(name asc)": PRODUCT_SEARCH_QUERYResult;
    "*[_type == \"product\" && slug.current == $slug ] | order(name asc) [0]": PRODUCT_BY_ID_QUERYResult;
    "*[_type == \"product\" && references(*[_type == \"category\" && slug.current == $categorySlug]._id)] | order(name asc)": PRODUCT_BY_CATEGORY_QUERYResult;
    "*[_type == 'sale'] | order(name asc)": SALE_QUERYResult;
    "*[_type == 'order' && clerkUserId == $userId] | order(orderData desc){\n    ...,products[]{\n      ...,product->\n    }\n  }": MY_ORDERS_QUERYResult;
  }
}
